apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-configmap
data:
  appsettings.json: |-
    {
      "Routes": [   
    {
      "ServiceKey": "Identity Service",
      "DownstreamPathTemplate": "/api/identity/{everything}",
      "DownstreamScheme": "{{ .Values.reRoutes.identityService.schema }}",
      "DownstreamHostAndPorts": [
        {
          "Host": "{{ .Values.reRoutes.identityService.host }}",
          "Port": {{ .Values.reRoutes.identityService.port }}
        }
      ],
      "UpstreamPathTemplate": "/api/identity/{everything}",
      "UpstreamHttpMethod": [ "Put", "Delete", "Get", "Post" ]
    },
    {
      "ServiceKey": "Identity Service",
      "DownstreamPathTemplate": "/api/account/{everything}",
      "DownstreamScheme": "{{ .Values.reRoutes.identityService.schema }}",
      "DownstreamHostAndPorts": [
        {
          "Host": "{{ .Values.reRoutes.identityService.host }}",
          "Port": {{ .Values.reRoutes.identityService.port }}
        }
      ],
      "UpstreamPathTemplate": "/api/account/{everything}",
      "UpstreamHttpMethod": [ "Put", "Delete", "Get", "Post" ]
    },
    {
      "ServiceKey": "Saas Service",
      "DownstreamPathTemplate": "/api/saas/{everything}",
      "DownstreamScheme": "{{ .Values.reRoutes.saasService.schema }}",
      "DownstreamHostAndPorts": [
        {
          "Host": "{{ .Values.reRoutes.saasService.host }}",
          "Port": {{ .Values.reRoutes.saasService.port }}
        }
      ],
      "UpstreamPathTemplate": "/api/saas/{everything}",
      "UpstreamHttpMethod": [ "Put", "Delete", "Get", "Post" ]
    },
    {
      "ServiceKey": "Administration Service",
      "DownstreamPathTemplate": "/api/abp/{everything}",
      "DownstreamScheme": "{{ .Values.reRoutes.administrationService.schema }}",
      "DownstreamHostAndPorts": [
        {
          "Host": "{{ .Values.reRoutes.administrationService.host }}",
          "Port": "{{ .Values.reRoutes.administrationService.port }}",
        }
      ],
      "UpstreamPathTemplate": "/api/abp/{everything}",
      "UpstreamHttpMethod": [ "Put", "Delete", "Get", "Post" ]
    },
    {
      "ServiceKey": "Administration Service",
      "DownstreamPathTemplate": "/api/feature-management/{everything}",
      "DownstreamScheme": "{{ .Values.reRoutes.administrationService.schema }}",
      "DownstreamHostAndPorts": [
        {
          "Host": "{{ .Values.reRoutes.administrationService.host }}",
          "Port": "{{ .Values.reRoutes.administrationService.port }}",
        }
      ],
      "UpstreamPathTemplate": "/api/feature-management/{everything}",
      "UpstreamHttpMethod": [ "Put", "Delete", "Get", "Post" ]
    },
    {
      "ServiceKey": "Administration Service",
      "DownstreamPathTemplate": "/api/permission-management/{everything}",
      "DownstreamScheme": "{{ .Values.reRoutes.administrationService.schema }}",
      "DownstreamHostAndPorts": [
        {
          "Host": "{{ .Values.reRoutes.administrationService.host }}",
          "Port": "{{ .Values.reRoutes.administrationService.port }}",
        }
      ],
      "UpstreamPathTemplate": "/api/permission-management/{everything}",
      "UpstreamHttpMethod": [ "Put", "Delete", "Get", "Post" ]
    },
    {
      "ServiceKey": "Administration Service",
      "DownstreamPathTemplate": "/api/setting-management/{everything}",
      "DownstreamScheme": "{{ .Values.reRoutes.administrationService.schema }}",
      "DownstreamHostAndPorts": [
        {
          "Host": "{{ .Values.reRoutes.administrationService.host }}",
          "Port": "{{ .Values.reRoutes.administrationService.port }}",
        }
      ],
      "UpstreamPathTemplate": "/api/setting-management/{everything}",
      "UpstreamHttpMethod": [ "Put", "Delete", "Get", "Post" ]
    }]
    }